### PR TITLE
Add external logger support.

### PR DESCRIPTION
**Pull request by AbelHu**

### CODE REVIEW

**Comment by devigned** [comment]
Please update the pr. This would be awesome to get into the gem.

**Comment by AbelHu** [comment]
The pr has been updated. Ready for merge.

**Comment by devigned** [comment]
Great! I'll review and get it pulled in.

**Comment by devigned** [comment]
Please add a test to this?

**Comment by AbelHu** [comment]
Test case is added for logger. CI failed because other test cases are not stable. How do I need to do?

**Comment by AbelHu** [comment]
Test case was added and CI build passed. Ready for merge.

**Comment by AbelHu** [comment]
What do I need to do to merge this pull request?

**Comment by devigned** [comment]
Thank you for the contribution

**Pull request merged**
