### PR TITLE
New SDKs for Resource, Storage, Network and Compute management

### PR DESCRIPTION
**Pull request by dmitriy-barkalov**
The PR includes:
1 Resource Management SDK gem 
2 Storage Management SDK gem
3 Network Management SDK gem
4 Compute Management SDK gem

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dmitriy-barkalov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by nicklebedev37** [comment]
A few known issues:
1. Header's text is cut - last word is missing.
2. Timeliness gem likely can be safely removed from dependencies since it is used only in the MsRest.

They will be fixed in the next PR.

**Comment by arax** [comment]
Hi guys, is there any chance this will be ready for early testing soon? Usable Alpha/Beta version would be completely fine and greatly appreciated :-)

Do you have an estimate for the first stable release?

Thank you!

**Comment by nicklebedev37** [comment]
Hey @arax , thanks for your interest and sorry for delay. Preliminary plan is to publish early alpha version of a few ARM SDKs on the next week. Stay tuned, updates should come shortly :)

**Comment by arax** [comment]
@nicklebedev37 Thanks!

**Comment by devigned** [comment]
Is this ready to be pulled in, or is work still being done?

**Comment by nicklebedev37** [comment]
We're still working on it in the feature/arm branch.

**Comment by arax** [comment]
@nicklebedev37 Do you see this code (in `feature/arm`) as an alpha version? In other words, usable for testing? Thanks!

**Comment by nicklebedev37** [comment]
Yes, it can used as an early alpha version.
But to make it work you'll need two gems which contain auxiliary functionality. These gems are in the repository https://github.com/Azure/autorest/ and their latest version are in the PR https://github.com/Azure/autorest/pull/310.

You need to either wait until the PR is merged or install gems from the fork https://github.com/nicklebedev37/autorest/tree/dev
The gems are under the folders https://github.com/nicklebedev37/autorest/tree/dev/ClientRuntimes/Ruby/ms-rest and https://github.com/nicklebedev37/autorest/tree/dev/ClientRuntimes/Ruby/ms-rest-azure

Sorry for delay and thanks for interest.

**Comment by arax** [comment]
No problem, I can definitely do that. Is there a roadmap for getting all these into beta and stable? A rough estimate is completely fine. Thanks again!

**Pull request merged**
