### PR TITLE
fix cli_path separator, fixes Azure/azure-sdk-for-ruby#2852

### PR DESCRIPTION
**Pull request by hunter86bg**
Signed-off-by: Strahil Nikolov <snikolov@worldbankgroup.org>

### CODE REVIEW

**Comment by hunter86bg** [comment]
@microsoft-github-policy-service agree [company="WBG"]

**Comment by hunter86bg** [comment]
@devigned , @jcookems , @thoward , @vishrutshah ,

Is it normal that the CI takes so long ?
Do I have to do anything else to get this one merged ?

**Comment by devigned** [comment]
Hi @hunter86bg, thank you for contributing to the project. Unfortunately, I have been active here in a _long_ time, so I'm not really up on the current state of the project.

Just based on what I see from activity on the repo, it doesn't look like CI has been getting exercised in quite some time.

@Petermarcu, @salameer, or @mayurid do you know who could comment on the state of this project?

**Comment by hunter86bg** [comment]
@devigned , it looks like the project is abandonware.

**Comment by salameer** [comment]
Hello @hunter86bg !

Apologies for the delay in responding here. 

The project has entered retirement phase back in February 2021 and is only accepting security fixes if any. more details can be found here:

https://github.com/Azure/azure-sdk-for-ruby#important-announcement

If your PR is relevant to such fixes please let us know and super apologies again for the delay.

**Comment by hunter86bg** [comment]
@salameer , thanks for reaponding.
The patch is supposed to fix the issue with a wrong az cli path on Windows without which Chef Kitchen cannot work.

**Comment by salameer** [comment]
Hello @hunter86bg 

I followed up with the team and unfortunately as mentioned in the [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement) this repo is no longer maintained as of Dec31st 2021. so unfortunately this PR wont qualify for merging in.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk

**Pull request closed without merging**
