### PR TITLE
SSL certificate check

### PR DESCRIPTION
**Pull request by bukk530**
Now checking SSL certificate as described in the issue #210

### CODE REVIEW

**Comment by devigned** [comment]
Are you running into on Windows?
Can you smash up the changes into 1 commit?

Also, I'm not sure how I feel about checking in the ca_bundle rather than using the system ca directory. I definitely think it's better than the alternative of using no peer verification. Thoughts?

**Comment by devigned** [comment]
I'm thinking this path might be a little less prone to future issues: https://gist.github.com/fnichol/867550.

**Comment by bukk530** [comment]
The problem about reading the ca from a system directory is that each system stores it in a different directory. However I've hardcoded the ca in the repository as I've seen doing this many times.
The strategy described here https://gist.github.com/fnichol/867550 would mean we have to create a generator that downloads and installs the ca each time one install this gem, am I right?
One last thing, instead of packing any trusted cert in the repository we could just use Microsoft ones, as done by Facebook in their PHP SDK: https://github.com/facebook/facebook-php-sdk-v4/blob/4.0-dev/src/Facebook/HttpClients/certs/DigiCertHighAssuranceEVRootCA.pem

**Comment by devigned** [comment]
@bukk530 if you would narrow it down to just the MS related certs. I'll get this pulled in. Great work and thank you for the contribution.

**Comment by devigned** [comment]
Closing based on #219 and #220. Thank you for the PR, but I don't think we should be in the business of distributing cert bundles.

**Pull request closed without merging**
