### PR TITLE
Allow for a publishsettings file to be provided for the certificate, solves #266

### PR DESCRIPTION
**Pull request by andrewelizondo**
This PR implements the ability for a user to provide a .publishsettings file to `management_certificate` and it will be parsed for the appropriate certificate, removing the need for an additional step to convert the .publishsettings file to a .pfx

This could potentially be extended later to parse for the subscription ID as well, but for now that hasn't been implemented here.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@andrewelizondo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
@andrewelizondo, nice! Could you add a unit test to ensure no future regressions?

**Comment by andrewelizondo** [comment]
@devigned I got a fixture in place and unit tests added, I don't see a situation where someone would try to load this as a string so I didn't add that test, but I can be convinced.

**Comment by devigned** [comment]
LGTM. Thank you, @andrewelizondo!

**Pull request merged**
