### PR TITLE
Blob service shared access signatures

### PR DESCRIPTION
**Pull request by rahim**
I still intend to add convenience methods for consistency on BlobService itself, but this is useable as is.

### CODE REVIEW

**Comment by rahim** [comment]
Ignore my comment above - I'm not convinced adding convenience methods on BlobService would be helpful, but happy to add if anyone thinks they are.

**Comment by devigned** [comment]
Please add an integration test showing it's usage via BlobService.

**Comment by devigned** [comment]
@rahim thank you for the great work

**Comment by rahim** [comment]
Pleasure! Apologies for not replying regarding the integration test, I'd been meaning to address that following your comment but I'd not yet found time.

**Comment by devigned** [comment]
No worries. You waited much longer for your reply on the pr :smile:

**Pull request merged**
