### PR TITLE
do not pollute root namespace

### PR DESCRIPTION
**Pull request by tandibar**
I am using the Azure gem in a project and had some wired problems defining a `Location` class. After some investigation I found out that the class clashes with the Azure::BaseManagement::Location class. This is because of the line `include Azure::BaseManagement` in `lib/azure/base_management/base_management_service.rb`. This is really bad as it messes with the root namespace. I removed the `include` and fixed all references. All tests are passing. I did the same with the `Loggerx` and the include of the core utils.

### CODE REVIEW

**Comment by devigned** [comment]
@tandibar and @mukaibot I'm sorry this didn't receive more attention previously.

I agree with the premise of the pull request. We should not pollute the root namespace as it can lead to nastiness up the dependency chain.

With that said, if you'd like to rebase and freshen this up, I'd reevaluate merging the PR.

**Comment by tandibar** [comment]
I merged current master with my changes. Hope you can accept this now. thx

**Comment by devigned** [comment]
LGTM

**Comment by tandibar** [comment]
Cool!

**Comment by devigned** [comment]
Thank you for the contribution!

**Pull request merged**
