### PR TITLE
Remove wrong content-encoding handling

### PR DESCRIPTION
**Pull request by nurse**
Content-Encoding header is not to specify character encodings, but
specify content compressing (encoding).
http://msdn.microsoft.com/ja-jp/library/windows/desktop/aa383955(v=vs.85).aspx

### CODE REVIEW

**Comment by nurse** [comment]
The wrong code still remain

**Comment by merqlove** [comment]
Same here. Tried to deploy GZIP and got `unknown encoding name: gzip`

**Comment by devigned** [comment]
Added in a large refactor: #248

**Comment by nurse** [comment]
Refactored one still has the same wrong code: https://github.com/devigned/azure-sdk-for-ruby/blob/master/service_management/azure/lib/azure/blob/blob_service.rb#L1376

**Comment by veronicagg** [comment]
@nurse Storage functionality is now in its own repo https://github.com/Azure/azure-storage-ruby, feel free to take a look/ open an issue there. thanks!

**Comment by nurse** [comment]
@veronicagg thanks, I create https://github.com/Azure/azure-storage-ruby/pull/52!

**Pull request closed without merging**
