### PR TITLE
Correct MetaDataContract  constant name

### PR DESCRIPTION
**Pull request by cuongn265**
Currently when I tried to call: 
```ruby
client = Azure::Face::Profiles::Latest::Client.new(options)
client.large_person_group_operations.create('missing_people', name: "Missing People")
```

Azure SDK return `NameError: uninitialized constant Azure::CognitiveServices::Face::V1_0::LargePersonGroupOperations::MetaDataContract` error due to wrong constant called.

### CODE REVIEW

**Comment by cuongn265** [comment]
Hello can anyone help? I'm stucking on this for a long time. cc @bim-msft, @MyronFanQiu as code owner

**Comment by nickzhums** [comment]
@MyronFanQiu could you take a look at this PR?

**Comment by MyronFanQiu** [comment]
@cuongn265 Can you share more information about your usage scenario? These codes are auto-generated and should not be modified manually in general. Meanwhile, there is a mapping in the definition. I don't understand the root cause for your error message.
https://github.com/Azure/azure-sdk-for-ruby/blob/d14a3c03bba09e1f4e2e2cac9b3b89fd77f203ad/data/azure_cognitiveservices_face/lib/profiles/latest/modules/face_profile_module.rb#L56

**Comment by cuongn265** [comment]
Hey @MyronFanQiu, thank you so much for the quick response. My scenario is just simple as it is, I was trying to create a `large person group`. What I did:
```ruby
credentials = MsRestAzure::CognitiveServicesCredentials.new(ENV['AZURE_FACE_SUBSCRIPTION_KEY'])

options = {
  tenant_id: ENV['AZURE_TENANT_ID'],
  client_id: ENV['AZURE_CLIENT_ID'],
  client_secret: ENV['AZURE_CLIENT_SECRET'],
  subscription_id: ENV['AZURE_SUBSCRIPTION_ID'],
  credentials: credentials
}

FaceClient = Azure::Face::Profiles::Latest::Client.new(options)
FaceClient.endpoint = ENV['AZURE_FACE_ENDPOINT']

FaceClient.large_person_group_operations.create('missing_people', name: 'Missing People', recognition_model: 'recognition_02')

### Error happen here:
NameError: uninitialized constant Azure::CognitiveServices::Face::V1_0::LargePersonGroupOperations::MetaDataContract
```

I was following exactly what document said but seem like code loader didn't recognize `MetaDataContract` in module `Models`.

You can see here in the same file: [link](https://github.com/Azure/azure-sdk-for-ruby/blob/d14a3c03bba09e1f4e2e2cac9b3b89fd77f203ad/data/azure_cognitiveservices_face/lib/profiles/latest/modules/face_profile_module.rb#L56) it have to explicit call `Azure::CognitiveServices::Face::V1_0::Models::MetaDataContract` over `MetaDataContract` only

**Comment by MyronFanQiu** [comment]
@cuongn265 Sure. Since it's auto-generated, I need to investigate the generation tool for ruby sdk. Due to low bandwidth, we need some time to fix this issue. Is it a blocker for you right now?

**Comment by cuongn265** [comment]
@MyronFanQiu it should block my work, but don't worry since I can work on my own fork. Happy to see you guys have a look on this. TIA

**Comment by nickzhums** [comment]
@cuongn265 Thanks for your feedback, I'm curious as why you have chosen to use the Ruby SDK instead of other languages (Java/Python/.NET) to manage Azure resources?

**Comment by MyronFanQiu** [comment]
@jiasli We can go through this issue together later.

**Comment by cuongn265** [comment]
I don't have any idea on this @nickzhums, Ruby is just my favorite language and I'm happy to work with these kind of stuffs.

**Comment by nickzhums** [comment]
> I don't have any idea on this @nickzhums, Ruby is just my favorite language and I'm happy to work with these kind of stuffs.

What are your scenarios and what resources are you managing?

**Comment by cuongn265** [comment]
> > I don't have any idea on this @nickzhums, Ruby is just my favorite language and I'm happy to work with these kind of stuffs.
> 
> What are your scenarios and what resources are you managing?

I'm on face recognition service @nickzhums

**Comment by jiasli** [comment]
@cuongn265, I am glad you have a workaround on this. However, we currently don't have enough bandwidth working on the Ruby SDK auto-generation. It will eventually be deprecated with the migration of Azure SDKs to **track 2 Azure Core**, such as the [Azure Core shared client library for Python](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/core/azure-core).

As @nickzhums pointed out, other SDKs like Python get more attention and we are actively working on it. Azure CLI itself is built on Python! 😉

**Comment by cuongn265** [comment]
@jiasli Thank you so much for the explanation, it would be good if you guys can tell me which tool are you doing to generate ruby sdk and is there any document to do it myself since I'm facing a lot of error relate to this one. Would love to see how to generator works and give a hand to debug

**Comment by MyronFanQiu** [comment]
@cuongn265  Hi. autorest autorest.ruby and [this one](https://github.com/Azure/azure-sdk-for-ruby/tree/master/generators)

**Review by tlvu2697 — APPROVED** [review]

**Comment by ArthurMa1978** [comment]
This repo [has entered a retirement phase and is no longer officially supported by Microsoft](https://github.com/Azure/azure-sdk-for-ruby#important-announcement).

**Pull request closed without merging**
