### PR TITLE
[ARM] Replace data from recordings even when they are encoded

### PR DESCRIPTION
**Pull request by vishrutshah**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by veronicagg** [comment]
@vishrutshah LGTM. Was this data not encoded in any case before, so we didn't see it?

**Comment by vishrutshah** [comment]
@veronicagg Before that i haven't used those keys that is not the same as the after encoding. I noticed it that [both are being encoded](https://github.com/Azure/autorest/blob/45ddc1a84c58f5732a2f77418079c9439f39e892/src/client/Ruby/ms-rest-azure/lib/ms_rest_azure/credentials/application_token_provider.rb#L100) so that we should also cover that case as well.

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
