### PR TITLE
adding documentation for initialization of profile clients

### PR DESCRIPTION
**Pull request by veronicagg**
Addressing https://github.com/Azure/azure-sdk-for-ruby/issues/1069
I've updated the comments for initialize method to indicate what the options should be, following our readme instructions - these should be in sync.
Let me know your feedback.

### CODE REVIEW

**Comment by veronicagg** [comment]
@sarangan12 thoughts?

**Comment by sarangan12** [comment]
I would recommend not to ad this now. Will discuss offline

**Comment by veronicagg** [comment]
ok, is it because you're making the other changes to remove the requirements? per https://github.com/Azure/azure-sdk-for-ruby/issues/1129
If so, we can either make these ones now, and update when you make your updates, or you can copy paste what's needed from this PR and include it in your changes. 
Let me know, thanks!

**Comment by veronicagg** [comment]
@sarangan12 it'd be good to merge this changes if we're not completing the related task soon. Feel free to do so, or publish a PR for the related issue.

**Comment by veronicagg** [comment]
Decided on merging, so let's resolve the conflict and commit.

**Pull request merged**
