### PR TITLE
Use pessimistic operation for azure_sdk's runtime dependecies

### PR DESCRIPTION
**Pull request by vishrutshah**

### CODE REVIEW

**Comment by vishrutshah** [comment]
@veronicagg & @sarangan12 Feel free to review this PR when you get a chance. Thanks!

**Comment by veronicagg** [comment]
@vishrutshah minor: you could also try to define a variable for "~>#{version}" and use that in the rest of the lines. thanks!

**Comment by vishrutshah** [comment]
@veronicagg As we discussed offline, this will change soon as we diverge all gems to different cadence, so let's keep it as it. 

@sarangan12 Please let me know your views on this PR. 

Thanks!

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
