### PR TITLE
Unpin version of unf_ext

### PR DESCRIPTION
**Pull request by gsreynolds**
Version was pinned to 0.0.7.2 in https://github.com/Azure/azure-sdk-for-ruby/pull/2457 but is no longer necessary

Dependency tree is 
```
ms_rest_azure
  faraday-cookie_jar (~> 0.0.6)
    http-cookie (~> 1.0.0)
      domain_name (~> 0.5)
        unf (>= 0.0.5, < 1.0.0)
          unf_ext (>= 0)
```

but ms_rest_azure currently has a specific version pin on unf_ext (= 0.0.7.2). This version constraint will conflict with other Ruby applications which are allowing latest unf_ext which is 0.0.7.6

>  this was due to missing ruby 2.6 builds for windows, which now seems to be fixed in 0.0.7.6?

See https://github.com/theforeman/foreman-packaging/pull/4179#issuecomment-543643279

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@gsreynolds Hello. Thanks for your contribution. I'm a new owner of ruby sdk and sorry I don't know the full context for this. Is it ok to use 0.0.7.6 instead?

**Comment by gsreynolds** [comment]
Yes, the reason for pinning to 0.0.7.2 last year is long resolved. Context is in the linked PR.

0.0.7.6 is fine to use, as far as I can tell. The Travis tests with 0.0.7.6 seem to have passed as well.

**Comment by gsreynolds** [comment]
Hi @MyronFanQiu, have you had a chance to review this change? Would be great if we could get a release of the gem with this version constraint removed 😄. Thanks!

**Comment by evgeni** [comment]
I (with my [@theforeman/foreman-packaging](https://github.com/theforeman/foreman-packaging) hat on) am super interested in this shipping :)

**Comment by MyronFanQiu** [comment]
@gsreynolds Sorry for the delay. I'm isolated at home right now. I would review the logic and help merge this PR

**Comment by ekohl** [comment]
@MyronFanQiu I hope you're doing well and can find some time to take a look at this.

**Comment by MyronFanQiu** [comment]
@gsreynolds Thanks! I would do it within days.

**Comment by MyronFanQiu** [comment]
@gsreynolds Thanks for your contribution.

**Pull request merged**
