### PR TITLE
Added support for setting Azure.config.management_certificate as a string

### LINKED ISSUE #183: Add support for passing file content directly for management_certificate
Currently the value of `Azure.config.management_certificate` can only be set as a file path. There is no provision of giving file content as a string directly instead of giving file path. Can we add a functionality where user can optionally set `Azure.config.management_certificate` as a string?

Also I would like to contribute in this issue if someone would approve of this feature.

reference: https://github.com/Azure/azure-sdk-for-ruby/blob/master/lib/azure/base_management/base_management_service.rb#L34

### PR DESCRIPTION
**Pull request by h4hardikonly**
Untill now management_certificate was only accepting file path. I've added support for accepting file content as raw string. 

fixes #183

### CODE REVIEW

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre

**Comment by h4hardikonly** [comment]
One concern ... Why copied code creating new branch instead of merging this PR .... 
Concern is that instead of real author the credit goes to other account
[https://github.com/Azure/azure-sdk-for-ruby/blame/master/lib/azure/base_management/base_management_service.rb#L25](https://github.com/Azure/azure-sdk-for-ruby/blame/master/lib/azure/base_management/base_management_service.rb#L25)

**Comment by devigned** [comment]
yes... I messed up the merge. I'm sorry. I know people put a bunch of their own time into these contributions and it's a bummer to not get the credit they rightly deserve.

Next time, I'll make sure to do it properly.

**Comment by devigned** [comment]
@h4hardikonly I really messed up the merge... The validation still checks for the file and your PR handles public only vs private and public better than master. Would you be interested in creating a new PR or updating this PR off of master. I'll pull it in, you'll get credit and the code will be correct. Thoughts?

#183

**Comment by h4hardikonly** [comment]
No worries boss :relaxed: ... I am reopening this PR after solving the merge conflicts with master.

**Pull request closed without merging**
