### PR TITLE
renamed Models folder to match case in azure_management_resources.rb

### PR DESCRIPTION
**Pull request by predeekc**
The case mismatch between the Models folder in the file structure of azure_management_resources and the azure_management_resources.rb file was causing issues on Linux.  I renamed the folder to match the file since that was the pattern in azure_management_storage.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@predeekc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@predeekc__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by devigned** [comment]
Fantastic! Thank you!

**Comment by gadgetmg** [comment]
Would it be possible to get a new gem uploaded to rubygems with this? Without it, using this gem on Linux isn't possible and there's no way I can find to point bundler to a subdirectory in a git repo.

**Comment by arax** [comment]
This issue affects all `azure_mgmt_*` gems in `resource_management`, not just `azure_mgmt_resources`. Is this something that has to be fixed in AutoRest (its Ruby generator) as well?

**Pull request merged**
