### PR TITLE
Remove data plane datalake from azure_mgmt_datalake_* gems

### PR DESCRIPTION
**Pull request by vishrutshah**
- Removing Job and Catalog & their specs from azure_mgmt_datalake_analytics
- Removing filesystem & their specs from azure_mgmt_datalake_store
- Updating `rake arm:regen` to not handle Arrayed inputs
- Updating Hand-written `azure_mgmt_datalake_analytics.rb` and `azure_mgmt_datalake_store.rb` to reference correct autog-enerated files
- Updating`azure_mgmt_datalake_analytics.gemspec` & `azure_mgmt_datalake_store.gemspec` to use correct namespace and require correct file paths
- Adding `azure_mgmt_datalake_store` & `azure_mgmt_datalake_analytics` into swagger to sdk pipeline

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vishrutshah** [comment]
@veronicagg Feel free to review this PR when you get a chance. Thanks!

**Comment by veronicagg** [comment]
@vishrutshah LGTM, thanks!

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
