### PR TITLE
Generate the Key Vault data plane client

### PR DESCRIPTION
**Pull request by cosmincojocar**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cosmincojocar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (cosmc). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by cosmincojocar** [comment]
What is the status of this PR? When are you going to review it?

**Comment by tlabeeuw** [comment]
@cosmincojocar We are looking for this exact functionality! Any reason it was closed? Is this branch working and merged with the latest master?

**Comment by cosmincojocar** [comment]
@takekazuomi The team maintaining this SDK wasn't interested to merge it.

**Comment by tlabeeuw** [comment]
@cosmincojocar and Azure team. Is there an alternative repo or way of doing this that is supported then?

**Pull request closed without merging**
