### PR TITLE
Add additionalInfo to CloudError

### PR DESCRIPTION
**Pull request by j5lim**
'additionalInfo', a new property added to ARM error contract, contains additional error information. For example, it will contain detailed policy violation error information when the request to ARM failed due to violation of Azure policies.

The changes are to allow deserializing additionalInfo in ARM error.

### CODE REVIEW

**Comment by veronicagg** [comment]
Thanks @j5lim ! PR looks good to me, @sarangan12 any concerns?

**Comment by j5lim** [comment]
@sarangan12 @bsiegel Could you please review the PR?

**Comment by sarangan12** [comment]
Everything looks fine. Running one final round of tests and will be merged tonight. (if everything passes)

**Comment by j5lim** [comment]
@sarangan12 Thank you!

**Pull request merged**
