### PR TITLE
Added support for reserved ips, static ips in subnet, and custom data when creating a deployment

### PR DESCRIPTION
**Pull request by nterry**

### CODE REVIEW

**Comment by nterry** [comment]
Here you go! I added this because I needed it for my work on the Azure BOSH CPI here: https://github.com/nterry/bosh_azure_cpi

**Comment by milgner** [comment]
Was just looking for this feature, will give it a try! :+1:

**Comment by nterry** [comment]
Woot!

**Comment by nterry** [comment]
Added some more useful stuff from @AbelHu, and added missing unit tests for them.

**Comment by nterry** [comment]
@bradygaster There are a lot of features missing for the ruby sdk and this is a major one... When can I expect this to be merged? Its been 22 days since i originally opened this...

**Comment by nterry** [comment]
@devigned I notice that you have made some recent commits. Can you review this and pull it in? This is definitely something that is needed, and I'd love to see it pulled in. Im tired of having to run my custom version... ;)

**Comment by devigned** [comment]
@nterry please leave out the version bump next time. We'll take care of that :). Thank you for the contribution :beer:

**Comment by nterry** [comment]
@devigned Awesome!!! Thanks! And ill keep that in mind ;)

**Pull request merged**
