### PR TITLE
[Do-not-merge] Explicit MSI - compute gem update and runtime update

### PR DESCRIPTION
**Pull request by veronicagg**
- Updates to azure_mgmt_compute gem to include new api-version and "Latest" profile pointing to latest package definition *Note SDK needs to get re-generated after https://github.com/Azure/azure-rest-api-specs/pull/2099 gets merged
- Updates ms_rest_azure to support 'client_id' parameter for MsiTokenProvider, to support explicit MSI (Managed Service Identity). 
- Pending update to ChangeLog, readme for ms_rest_azure
- Pending update to swagger_to_sdk_config.json
- Not planning on re-releasing roll-up gem

Made several commits to help with review.
Code is pending testing against real service.

@lmazuel @yugangw-msft does this account for the required changes?
FYI - @salameer @jhendrixMSFT 

Addressing https://github.com/Azure/azure-sdk-for-ruby/issues/1175

### CODE REVIEW

**Comment by anuchandy** [comment]
@veronicagg virtual_machine_identity_type.rb is missing identitiesIds property that stores the associated Explicit MSI references. It seems the compute swagger PR with this update is yet to merge https://github.com/Azure/azure-rest-api-specs/pull/2099

**Comment by veronicagg** [comment]
@anuchandy yes, completely correct! I will add this to the pending items above. 
Basically, I generated code out of the latest in master as I saw that the latest package for compute contained updated and multiple API versions (which were present in the repo), to make sure our Ruby compute package would be proper picking up these and generating a "profile" with the appropriate versions. The contents (commit hash) used for generation would need to be updated to the commit that contains the changes and things re-generated. 
All these changes still need to be validated too.

**Comment by lmazuel** [comment]
I don't know Ruby, but folders 2017-03-30/2017-09-01/2017-12-01 sounds structure. With what you said, I think it's good

**Comment by veronicagg** [comment]
Runtime updates for user assigned identity were merged with PR https://github.com/Azure/azure-sdk-for-ruby/pull/1194. Other than that this PR is old, so closing.

**Pull request closed without merging**
