### PR TITLE
Moving Azure classic (asm) source code to asm brach & deleting from master

### PR DESCRIPTION
**Pull request by vishrutshah**
We have been experimenting with the Azure Resource Manager set of Ruby client libraries at https://github.com/Azure/azure-sdk-ruby. Now we are reorganizing this repository as the place to keep ASM & ARM version of the source code with `master `and `asm `branch respectively. 

ASM Ruby Client: https://github.com/Azure/azure-sdk-for-ruby/tree/asm
ARM Ruby Client: https://github.com/Azure/azure-sdk-for-ruby

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by veronicagg** [comment]
@vishrutshah LGTM

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Pull request merged**
