### PR TITLE
[azure_mgmt_*] Prepare to release azure_mgmt_* version 0.12.0 

### PR DESCRIPTION
**Pull request by vishrutshah**
Regarding https://github.com/Azure/azure-sdk-for-ruby/issues/958

- [x] Regen all azure_mgmt_* sdks using AzureRest.Ruby version [1.9.3](https://www.npmjs.com/package/@microsoft.azure/autorest.ruby)
- [x] **Skip** generation of `azure_mgmt_traffic_manager` due to https://github.com/Azure/autorest.ruby/pull/7
- [x] **Skip** generation of `azure_mgmt_web` due to https://github.com/Azure/azure-sdk-for-ruby/issues/957
- [x] Update ARM_VERSION file to `0.12.0`
- [x] Update swagger_to_sdk config file to version `0.12.0`
- [x] Incorporate change https://github.com/Azure/azure-rest-api-specs/pull/1658#issuecomment-328257061 into `azure_mgmt_comput` gem
- [x] Update changelog
- [x] Update all azure_mgmt_* sdks' `.gemspec` file to depend on `ms_rest_azure` version `~>0.9.0`
- [x] Update release process documentation w.r.t `AutoRest.Ruby` generator

### CODE REVIEW

**Comment by veronicagg** [comment]
@vishrutshah question: the change that's marked as reverted above, takes me automatic PR 
 https://github.com/Azure/azure-sdk-for-ruby/pull/934 that comes from https://github.com/Azure/azure-rest-api-specs/pull/1574 This PR doesn't seem to contain the ResourceUpdate changes, what am I missing?

**Comment by vishrutshah** [comment]
@veronicagg That's a right question but as i was just making commits to unblock my task this PR appears here. Could you please reivew https://github.com/Azure/azure-sdk-for-ruby/pull/959/files#diff-12caea728ed994cf224b6432d02d995eR11 first and see if I missed anything here. If i missed it should be there as well. Thanks!

**Comment by veronicagg** [comment]
Rest looks good to me. Could you update our instructions on the release process? now that we have the Autorest.Ruby repo?

**Comment by vishrutshah** [comment]
Below is the remaining checklist for me:

- [ ] Incorporate change https://github.com/Azure/azure-rest-api-specs/pull/1658#issuecomment-328257061 into `azure_mgmt_comput` gem
- [ ] Update changelog
- [ ] Update release process documentation w.r.t `AutoRest.Ruby` generator

**Comment by vishrutshah** [comment]
Thanks for the review!! I'll wait for @sarangan12 to go over this as well to make sure things looks good.

**Comment by sarangan12** [comment]
LGTM

**Comment by vishrutshah** [comment]
Thanks @sarangan12 for taking a look.

**Pull request merged**
